version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: smolathon_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/001_init.up.sql:/docker-entrypoint-initdb.d/001_init.up.sql

  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: smolathon_db
      JWT_SECRET: your-super-secret-jwt-key-here

volumes:
  postgres_data:
